### ISSUE TITLE
Module parse fail error.

### ISSUE THREAD

**Issue by ionicankit** [PeterKassenaar/ng2-webcam#1]
ERROR in ./~/ng2-webcam/lib/fallback/jscam_canvas_only.swf
Module parse failed: E:\identidata-19\node_modules\ng2-webcam\lib\fallback\jscam_canvas_only.swf Unexpected character ' (1:3)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

**Comment by sw-angel** [comment]
Is there solution how to handle the below issue

Module parse failed: C:\Users\sample\Documents\work\projects\kmc-visitorlogin\node_modules\ng2-webcam\lib\fallback\jscam_canvas_only.swf Unexpected character '' (1:3)
You may need an appropriate loader to handle this file type.

**Comment by PeterKassenaar** [comment]
I haven't looked into this issue yet. Is it reproducable across browsers?

**Comment by ghost** [comment]
Same Problem here,

It's not due to browsers, it's a compilation problem.
Here's the full stack:

ERROR in ./ng2-webcam/lib/fallback/jscam_canvas_only.swf
Module parse failed: C:\Users\XXX\Documents\XXX\XXX\anom-XXX\node_modules\ng2-webcam\lib\fallback\jscam_canvas_only.swf Unexpected character ' (1:3)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/ng2-webcam/index.ts 3:0-46
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./ng2-webcam/lib/fallback/jscam.swf
Module parse failed: C:\Users\XXX\Documents\XXX\XXX\anom-XXX\node_modules\ng2-webcam\lib\fallback\jscam.swf Unexpected character ' (1:3)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/ng2-webcam/index.ts 4:0-34
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

Is there any solutions?

**Comment by ToastyMallows** [comment]
Same issue here.  Fresh workspace using `ng new` and `npm install ng2-webcam --save-dev`.  I then added a reference to the WebCamComponent, and used `npm start` to compile and run, got the same error as above.

**Comment by AckerApple** [comment]
CAUSE OF ISSUE : ng2-webcam auto imports an swf as a fallback and only webpack can make sense of importing a binary swf during the compilation process (using some sort of loader). You cannot load files that Typescript has not been instructed how to use.

FIX : Use my fork of ng2-webcam AND follow instructions for runtime fallback which calls for the swf file OUTSIDE of compilation processes. My fork is called ack-angular-webcam as seen here https://www.npmjs.com/package/ack-angular-webcam

**Comment by basst314** [comment]
I'm also experiencing this issue in a fresh angular-cli project. Same error as @ToastyMallows already mentioned.
@PeterKassenaar will this issue be resolved? (open since may)

**Comment by AckerApple** [comment]
Just use ack-angular-webcam. Same package, its a fork of this package. Follow my previous comments

**Comment by PeterKassenaar** [comment]
@basst314 - Sorry, not working on this project anymore (and no time/urgence to update). 

I suggest you go for the fork @AckerApple already mentioned if you need webcam functionality in Angular: https://www.npmjs.com/package/ack-angular-webcam 

Thank  you.
